import { Artist } from './datatypes';
export const artists_hairstylists: Artist[] = [
{
name: "Rhonda Marttunen",
position: "Hairstylist & Owner",
bio: "With over 30 years of experience, Rhonda has expertise in many services, including cuts, colours, highlights, and balayage, and is also certified in fusion hair extensions. She continues to grow her repertoire by staying up to date on current trends while preserving the health of the client's hair. Rhonda has built a dedicated clientele since arriving to St Thomas in 2016, as she consistently listens to her clients, delivering stunning looks each time. Don't hesitate - book with Rhonda today and let her help you achieve your dream hair!",
primaryButtonText: "Text: (226) 998-1227",
primaryButtonLink: "sms:+12269981227",
secondaryButtonText: "Call: (519) 207-1111",
secondaryButtonLink: "tel:15192071111",
isAcceptingNewClients: true,
services: [
{type: "group",name: "Haircuts",description: "Additional time charge for extra long or thick hair",},
{type: "item",name: "Woman's Haircut",price: "$35+",},
{type: "item",name: "Men's Haircut",price: "$25+",},
{type: "item",name: "Kid's Haircut",price: "$25+",description: "Ages 12 and Under",},
{type: "subgroup",name: "Haircut Add-Ons",},
{type: "item",name: "Wash",price: "$5",},
{type: "item",name: "Style for Short Hair",price: "$5",description: "Curl or Straighten",},
{type: "item",name: "Style for Long Hair",price: "$10+",description: "Curl or Straighten, Shoulder Length Hair and Longer",},
{type: "group",name: "Hair Styling",},
{type: "item",name: "Wash & Style for Short Hair",price: "$28",},
{type: "item",name: "Wash & Style for Long Hair",price: "$40+",description: "Shoulder Length Hair and Longer",},
{type: "item",name: "Updo",price: "$80+",},
{type: "group",name: "Colours & Highlights",},
{type: "subgroup",name: "Colours",description: "Additional charge for each extra bowl of colour used",},
{type: "item",name: "Root Re-Touch",price: "$75+",},
{type: "item",name: "Full Colour",price: "$125+",},
{type: "item",name: "Express Colour",price: "$75+",description: "Nine Minute Processing Time, Limited Colour Options",},
{type: "item",name: "Colour Correction",price: "$250+",},
{type: "subgroup",name: "Highlights",},
{type: "item",name: "Partial Highlights",price: "$80+",},
{type: "item",name: "Three-Quarter Highlights",price: "$100+",},
{type: "item",name: "Full Highlights",price: "$130+",},
{type: "subgroup",name: "Colour & Highlight Combos",},
{type: "item",name: "Root Re-Touch + Partial Highlights",price: "$135",},
{type: "item",name: "Root Re-Touch + Three-Quarter Highlights",price: "$155",},
{type: "item",name: "Root Re-Touch + Full Highlights",price: "$185",},
{type: "item",name: "Full Colour + Full Highlights",price: "$235+",},
{type: "group",name: "Balayage",},
{type: "item",name: "Balayage",price: "$200+",},
{type: "item",name: "Foilayage",price: "$200+",},
{type: "item",name: "Ombre",price: "$200+",},
{type: "group",name: "Toner",},
{type: "item",name: "Toner (Short Hair)",price: "$50",},
{type: "item",name: "Toner (Long Hair)",price: "$75+",description: "Shoulder Length Hair and Longer",},
{type: "group",name: "Extensions",description: "Fusion Hair Extensions",},
{type: "item",name: "Partial Extensions",price: "$250+",},
{type: "item",name: "Three-Quarter Extensions",price: "$350+",},
{type: "item",name: "Full Extensions",price: "$450+",},
],
},
{
name: "Victoria Butler",
position: "Hairstylist",
bio: "Victoria (Ria) is a St. Thomas based licensed hairstylist, who has worked in the industry since 2014. She has trained with celebrity hair stylists, worked on magazine photo shoots, and prioritizes the integrity of the hair while achieving your desired look. Victoria is a client-centric stylist, who loves to pair a client's at-home hair care routine with their hair goals to ensure they can recreate their style in every day life. She specializes in corrective colour and foiling, also offering a variety of cutting and facial waxing services. Click the link to BOOK ONLINE with Victoria today!",
primaryButtonText: "Book Online",
primaryButtonLink: "https://www.fresha.com/a/luxe-hair-artistry-co-st-thomas-20-churchill-crescent-d3m2puen/booking?menu=true&dppub=true&employeeId=1196989",
secondaryButtonText: "Text: (519) 207-1111",
secondaryButtonLink: "tel:15192071111",
externalServicesLink: "https://www.fresha.com/a/luxe-hair-artistry-co-st-thomas-20-churchill-crescent-d3m2puen/booking?menu=true&dppub=true&employeeId=1196989",
isAcceptingNewClients: true,
},
{
name: "Amanda Arends",
position: "Junior Hairstylist",
bio: "Special! 10% off all services when you book with Amanda! Please note that the listed prices include the discount.\nAmanda is a junior hairstylist. She completed the hairstyling program at Wheable in November 2023. As part of her program, she did a co-op placement at For The Look Salon and Spa in Dorchester and at First Choice Haircutters. After excelling in her courses, she is excited to begin her new career.",
primaryButtonText: "Book Online",
primaryButtonLink: "https://squareup.com/appointments/book/k2t8zozwpu8n5w/LZ0J6HENZDD2W/start",
secondaryButtonText: "Text: (519) 207-1111",
secondaryButtonLink: "tel:15192071111",
externalServicesLink: "https://squareup.com/appointments/book/k2t8zozwpu8n5w/LZ0J6HENZDD2W/start",
isAcceptingNewClients: true,
},
];
export const artists_aestheticians: Artist[] = [
{
name: "Kim Ferguson",
position: "Certified Aesthetician & Owner of The Orchid Room at Luxe",
bio: "Kim has been a certified aesthetician for nearly 25 years. Originally hailing from Barrie, Ontario, Kim owned a successful day spa there for 14 years before moving to beautiful St.Thomas in 2017. Since that time, Kim has gained a loyal clientele as a result of her precision and great attention to detail.\nKim feels it's of the utmost importance to stay informed on the upcoming trends and the best, safest practices for her clients. She enjoys working with new innovative products and services and has mentored new upcoming aestheticians to the industry.\nKim has a passion for Natural Nail enhancements that protect the health of her client's nails. She takes particular pride in being able to provide her clients with a wide variety of nail art. Feel free to come with ideas! Her experience covers a range of aesthetic services from laser hair removal, medical facials, sugaring, lash extensions and medical pedicures.\nKim looks forward to the chance to pamper you.",
primaryButtonText: "Text: (437) 385-8925",
primaryButtonLink: "sms:+14373858925",
isAcceptingNewClients: true,
services: [
{type: "group",name: "Natural Nail Enhancements",},
{type: "subgroup",name: "BioSculpture Gel",description: "BioSculpture Gel is a Superior product making nails beautiful, flexible and durable, without any Damage. It is a one step system that strengthens and promotes the growth of natural nails. It is applied onto the natural nail or used to create strong and comfortable tips for added length. ",},
{type: "item",name: "Full Cover Tips",price: "$95",description: "Instantly creating perfect shape and length natural looking nails. BioSculptures Full Cover tips use soft gel adhesion technology to bring you the strongest most comfortable tips on the market. No Glue, odours, dust, fumes or excessive filing to preserve the health of your natural nail. ",},
{type: "item",name: "Overlay",price: "$65",description: "BioSculpture Gel is applied to the natural nail, it strengthens and promotes natural nail growth.  The Gel is cured under a UV light, leaving the nail strong but flexible with a natural glossy or high shine finish.",},
{type: "item",name: "Fill or Soak Off with Reapplication",price: "$70",description: "Reapplication of BioSculpture overlay. Depending on your nail type the gel will be rebalanced or removed with gel remover before a new application of nourishing gel. ",},
{type: "subgroup",name: "Evo by BioSculpture",description: "Evo is a revolutionary colour system that has evolved from the BioSculpture gel system. It boasts the latest technology in gel Formulations. Infused with Vitamin A and E leaving the naIl nourished and rehydrated  Evos medical grade formula maintains and promotes healthy natural nails. ",},
{type: "item",name: "Evo Gel Polish Manicure",price: "$65",description: "The Gel polish system consists of three base gels, each having a unique texture and purpose to treat different nail types. Applied to the Natural nail it is extremely durable, long lasting, high shine gel.",},
{type: "item",name: "Evo Gel Polish Pedicure  ",price: "$75",description: "Upgrade your signature pedicure for a long lasting, durable gel polish on your toes.  Service includes foot soak, nails trimmed and shaped, cuticle and callus work. Gel is applied to the nails. Complete the pedicure with a relaxing massage and exfoliation with sugar scrub then wrapped in a hot towel. ",},
{type: "subgroup",name: "Add-Ons",},
{type: "item",name: "Add Full Cover Tip",price: "$5 per Nail",},
{type: "item",name: "Advanced Nail Design",price: "$5 per Nail, $20 per 5 Nails, $30 per 10 Nails",},
{type: "group",name: "Fingers & Toes",},
{type: "item",name: "Express Mani",price: "$30",description: "Nails trimmed and shaped, finished with a hydrating cream.",},
{type: "item",name: "Spa Manicure",price: "$50",description: "Nails shaped, cuticle work. Hands are massaged. Finish the treatment with a polish application.",},
{type: "item",name: "Express Pedi",price: "$45",description: "Foot soak, Nail trimmed and shaped finished with a hydrating cream.",},
{type: "item",name: "Sports Pedicure",price: "$55",description: "Foot soak, Nails trimmed and shaped, cuticle and callus work. Finished with a massage.",},
{type: "item",name: "Spa Pedicure",price: "$65 (Without Polish $60)",description: "Foot soak, Nails trimmed and shaped, cuticle and callus work. Feet are massaged and  exfoliated with sugar scrub wrapped in a hot towel. Finish the treatment with a polish application.",},
{type: "item",name: "Gentleman's Pedicure",price: "$60",description: "Foot soak, Nails trimmed and shaped, cuticle and callus work. Feet are massaged and  exfoliated with sugar scrub wrapped in a hot towel. ",},
{type: "group",name: "The B/S Brace System",description: "A NON-Surgical, corrective procedure that will eliminate pain and help correct the curvature of the nail",},
{type: "item",name: "Add Brace Nail",price: "$30",},
{type: "item",name: "Add 2 Brace Nails",price: "$50",},
{type: "group",name: "Lash Extensions",},
{type: "item",name: "Full Set",price: "$160",},
{type: "item",name: "2 Week Fill",price: "$60",},
{type: "item",name: "3 Week Fill",price: "$70",},
{type: "item",name: "4 Week Fill",price: "$80",},
{type: "group",name: "Waxing & Sugaring",},
{type: "subgroup",name: "Face",},
{type: "item",name: "Brows",price: "$24",},
{type: "item",name: "Upper Lip",price: "$15",},
{type: "item",name: "Chin",price: "$18",},
{type: "item",name: "Full Face",price: "$45",},
{type: "subgroup",name: "Body",},
{type: "item",name: "Brazilian",price: "$70",},
{type: "item",name: "Bikini",price: "$45",},
{type: "item",name: "Extended Bikini",price: "$55",},
{type: "item",name: "Underarms",price: "$20",},
{type: "item",name: "Full Arm",price: "$30",},
{type: "item",name: "Full Leg",price: "$80",},
{type: "item",name: "Half Leg",price: "$45",},
{type: "subgroup",name: "Combo",},
{type: "item",name: "Brazilian + Full Leg",price: "$130",},
{type: "item",name: "Bikini + Full Leg",price: "$115",},
{type: "item",name: "Brazilian + Underarms",price: "$85",},
{type: "item",name: "Brows + Upper Lip",price: "$34",},
{type: "subgroup",name: "Men",},
{type: "item",name: "Chest",price: "$50",},
{type: "item",name: "Back",price: "$50",},
{type: "group",name: "Tinting",},
{type: "item",name: "Eyelashes",price: "$35",},
{type: "item",name: "Brows",price: "$25",},
{type: "item",name: "Brow Wax & Tint",price: "$35",},
],
},
{
name: "Megan Hummel",
position: "Certified Aesthetician",
bio: "Megan Hummel is a Certified Medical Aesthetician with four years of experience, specializing in lash extensions and brow artistry. Originally from Kitchener, Megan relocated to St. Thomas four years ago, bringing her passion for aesthetics to the community. Her expertise extends beyond lash extensions, as she is also a certified Ombre powder brow and permanent makeup artist, showcasing her versatile skill set.\nWith a deep love for all aspects of aesthetics, Megan excels in providing top-notch services including facials, waxing, and massage therapy. What sets Megan apart is her dedication to listening to her clients' requests and ensuring that she takes the necessary time to deliver consistent and quality work. Her commitment to excellence and her genuine care for her clients have earned her a strong reputation in the industry.\nMegan's clients appreciate her attention to detail, personalized approach, and her ability to create stunning transformations while prioritizing their comfort and satisfaction. She has a true passion for enhancing natural beauty and empowering her clients.",
primaryButtonText: "Text: (437) 385-8925",
primaryButtonLink: "sms:+14373858925",
isAcceptingNewClients: true,
services: [
{type: "group",name: "Natural Nail Enhancements",},
{type: "subgroup",name: "BioSculpture Gel",description: "BioSculpture Gel is a Superior product making nails beautiful, flexible and durable, without any Damage. It is a one step system that strengthens and promotes the growth of natural nails. It is applied onto the natural nail or used to create strong and comfortable tips for added length. ",},
{type: "item",name: "Full Cover Tips",price: "$95",description: "Instantly creating perfect shape and length natural looking nails. BioSculptures Full Cover tips use soft gel adhesion technology to bring you the strongest most comfortable tips on the market. No Glue, odours, dust, fumes or excessive filing to preserve the health of your natural nail. ",},
{type: "item",name: "Overlay",price: "$65",description: "BioSculpture Gel is applied to the natural nail, it strengthens and promotes natural nail growth.  The Gel is cured under a UV light, leaving the nail strong but flexible with a natural glossy or high shine finish.",},
{type: "item",name: "Fill or Soak Off with Reapplication",price: "$70",description: "Reapplication of BioSculpture overlay. Depending on your nail type the gel will be rebalanced or removed with gel remover before a new application of nourishing gel. ",},
{type: "subgroup",name: "Evo by BioSculpture",description: "Evo is a revolutionary colour system that has evolved from the BioSculpture gel system. It boasts the latest technology in gel Formulations. Infused with Vitamin A and E leaving the naIl nourished and rehydrated  Evos medical grade formula maintains and promotes healthy natural nails. ",},
{type: "item",name: "Evo Gel Polish Manicure",price: "$65",description: "The Gel polish system consists of three base gels, each having a unique texture and purpose to treat different nail types. Applied to the Natural nail it is extremely durable, long lasting, high shine gel.",},
{type: "item",name: "Evo Gel Polish Pedicure  ",price: "$75",description: "Upgrade your signature pedicure for a long lasting, durable gel polish on your toes.  Service includes foot soak, nails trimmed and shaped, cuticle and callus work. Gel is applied to the nails. Complete the pedicure with a relaxing massage and exfoliation with sugar scrub then wrapped in a hot towel. ",},
{type: "subgroup",name: "Add-Ons",},
{type: "item",name: "Add Full Cover Tip",price: "$5 per Nail",},
{type: "item",name: "Advanced Nail Design",price: "$5 per Nail, $20 per 5 Nails, $30 per 10 Nails",},
{type: "group",name: "Fingers & Toes",},
{type: "item",name: "Express Mani",price: "$30",description: "Nails trimmed and shaped, finished with a hydrating cream.",},
{type: "item",name: "Spa Manicure",price: "$50",description: "Nails shaped, cuticle work. Hands are massaged. Finish the treatment with a polish application.",},
{type: "item",name: "Express Pedi",price: "$45",description: "Foot soak, Nail trimmed and shaped finished with a hydrating cream.",},
{type: "item",name: "Sports Pedicure",price: "$55",description: "Foot soak, Nails trimmed and shaped, cuticle and callus work. Finished with a massage.",},
{type: "item",name: "Spa Pedicure",price: "$65 (Without Polish $60)",description: "Foot soak, Nails trimmed and shaped, cuticle and callus work. Feet are massaged and  exfoliated with sugar scrub wrapped in a hot towel. Finish the treatment with a polish application.",},
{type: "item",name: "Gentleman's Pedicure",price: "$60",description: "Foot soak, Nails trimmed and shaped, cuticle and callus work. Feet are massaged and  exfoliated with sugar scrub wrapped in a hot towel. ",},
{type: "group",name: "The B/S Brace System",description: "A NON-Surgical, corrective procedure that will eliminate pain and help correct the curvature of the nail",},
{type: "item",name: "Add Brace Nail",price: "$30",},
{type: "item",name: "Add 2 Brace Nails",price: "$50",},
{type: "group",name: "Lash Extensions",},
{type: "item",name: "Full Set",price: "$160",},
{type: "item",name: "2 Week Fill",price: "$60",},
{type: "item",name: "3 Week Fill",price: "$70",},
{type: "item",name: "4 Week Fill",price: "$80",},
{type: "group",name: "Waxing & Sugaring",},
{type: "subgroup",name: "Face",},
{type: "item",name: "Brows",price: "$24",},
{type: "item",name: "Upper Lip",price: "$15",},
{type: "item",name: "Chin",price: "$18",},
{type: "item",name: "Full Face",price: "$45",},
{type: "subgroup",name: "Body",},
{type: "item",name: "Brazilian",price: "$70",},
{type: "item",name: "Bikini",price: "$45",},
{type: "item",name: "Extended Bikini",price: "$55",},
{type: "item",name: "Underarms",price: "$20",},
{type: "item",name: "Full Arm",price: "$30",},
{type: "item",name: "Full Leg",price: "$80",},
{type: "item",name: "Half Leg",price: "$45",},
{type: "subgroup",name: "Combo",},
{type: "item",name: "Brazilian + Full Leg",price: "$130",},
{type: "item",name: "Bikini + Full Leg",price: "$115",},
{type: "item",name: "Brazilian + Underarms",price: "$85",},
{type: "item",name: "Brows + Upper Lip",price: "$34",},
{type: "subgroup",name: "Men",},
{type: "item",name: "Chest",price: "$50",},
{type: "item",name: "Back",price: "$50",},
{type: "group",name: "Tinting",},
{type: "item",name: "Eyelashes",price: "$35",},
{type: "item",name: "Brows",price: "$25",},
{type: "item",name: "Brow Wax & Tint",price: "$35",},
],
},
];
